name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    tags:
      - 'v*'
    branches:
      - master

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: ks-upgrade
  IMAGE_REPO: kubespheredev
  IMAGE_VERSION: latest

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push image
        run: |
          IMAGE_ID=$IMAGE_REPO/$IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID
          docker buildx build --platform linux/amd64,linux/arm64 .  --push --file Dockerfile --tag $IMAGE_ID:IMAGE_VERSION