name: NightlyBuild

on:
  schedule:
    - cron: '15 17 * * *'
  workflow_dispatch:

jobs:
  buildx:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prepare
        run: |
          VERSION="nightly-$(TZ=Asia/Shanghai date +"%Y%m%d")"
          echo ::set-output name=version::${VERSION}

      - name: Docker meta for kubesphere
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: docker.io/kubesphere/ks-upgrade
          tags: ${{ steps.prepare.outputs.version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          push: true
          load: false
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64